[뉴스 뷰어 페이지 - 1단계] 이수진 미션 제출합니다.
LIN-KHU/javascript-newsviewer pull request #1
Opened 2024-01-21 18:14 UTC by sujin0707

2024-01-24 03:05 UTC, tkdrb12 requested changes
안녕하세요 수진님!
이번 미션도 진행하시느라 고생많았습니다!!

Tab 기능에서 마우스 오버 효과를 넣거나 따로 기사에서 링크로 연결되는 기능을 넣어주신 것처럼 
세심한 부분에서 많이 고민을 해주신 것 같아 좋았습니다.
저는 이런 디테일이 UI/UX를 향상시킨다고 생각하거든요!😀

코드 가독성도 전반적으로 향상된 것 같습니다 
하지만 미션 2단계에서는 역할 단위를 나누어 `컴포넌트` 별로 코드 단락을 분리하는 연습을 해보셨스연 좋겠습니다. 코드 단락을 역할에 따라 나누다보면 여러 이점을 챙길 수 가 있기 때문입니다~

2024-01-24 03:05 UTC, tkdrb12 commented on index.html
> +    <script src="index.js"></script>
스크립트는 빌드 시 webpack이 번들링하는 과정을 거치기 때문에 html내에 정의할 필요가 없습니다!

2024-01-24 03:05 UTC, tkdrb12 commented on package.json
> +    "async": "^3.2.5",
async를 따로 패키지 파일에 정의한 이유는 무엇인가요?

2024-01-24 03:05 UTC, tkdrb12 commented on src/index.js
>      console.log(process.env.API_KEY);
console.log는 결과물에서 제거해주시는 게 좋습니다

2024-01-24 03:05 UTC, tkdrb12 commented on src/index.js
> +    this.currentTabName = tabName;
해당 코드 라인은 따로 유의미하게 동작하지 않는 것 같은데 작성해주신 이유가 있으신가요?

2024-01-24 03:05 UTC, tkdrb12 commented on src/styles/index.css
> +nav a:hover:after {
이런 디테일이 ui의 퀄리티를 향상시킨다고 생각합니다👍

2024-01-24 03:05 UTC, tkdrb12 commented on src/index.js
> +  }
저번 1~2주차때 진행한 카드게임 미션을 기억하시나요?
그때 Card클래스로 Card의 기능을 분리했던 것 처럼 이 Tab 요소의 기능을 따로 클래스로 분리하는 연습을 해보시면 좋을 것 같습니다!
따로 역할을 분리해서 관리하면 재사용을 할 때 이점을 가질 수 있습니다!

2024-01-24 03:05 UTC, tkdrb12 commented on src/index.js
> +        <p class="meta-info">${authorInfo}&nbsp&nbsp&nbsp&nbsp${article.publishedAt}<button class="button-arrow" onclick="window.open('${article.url}', '_blank')"></button></p>
기사로 연결되도록 구현해주신 것 아주 좋습니다!😀

2024-01-24 03:05 UTC, tkdrb12 commented on src/styles/index.css
> +  content: '>';
따로 after 구문을 사용해서 `>`문자를 넣어준 이유가 있을까요?

2024-01-28 05:57 UTC, sujin0707 commented on index.html
> +    <script src="index.js"></script>
네 알겠습니다 삭제하겠습니다!

2024-01-28 05:58 UTC, sujin0707 commented on package.json
> +    "async": "^3.2.5",
아마 당시에 async를 사용할 때 오류가 생겨서 추가했었던 것 같습니다

2024-01-28 05:58 UTC, sujin0707 commented on src/index.js
>      console.log(process.env.API_KEY);
넵 제거하도록 하겠습니다

2024-01-28 05:59 UTC, sujin0707 commented on src/index.js
> +    this.currentTabName = tabName;
기본적으로 currentTabName이 general로 되어있기 때문에 클릭 시 현재의 tabname을 클릭한 tabname으로 바꾸어야 함수가 정상적으로 동작한다는 생각을 가지고 있었습니다

2024-01-28 05:59 UTC, sujin0707 commented on src/styles/index.css
> +nav a:hover:after {
감사합니다!

2024-01-28 05:59 UTC, sujin0707 commented on src/index.js
> +  }
2단계 미션 진행 해보면서 한번 분리해 보겠습니다

2024-01-28 06:00 UTC, sujin0707 commented on src/styles/index.css
> +  content: '>';
버튼의 모양을 > 모양으로 만들고 싶어서 넣었습니다

2024-01-28 06:42 UTC, tkdrb12 commented on src/styles/index.css
> +  content: '>';
2단계 미션에서는 문자가 아닌 svg 파일을 활용해서 바꿔보셨으면 좋겠어요!

https://icones.js.org/

2024-01-28 06:44 UTC, tkdrb12 approved these changes
수진님 1단계 미션 고생하셨습니다!
하지만 리팩토링 사항이 없어보이는데요ㅠㅜ 혹시 push가 누락된 건가요?
2단계에서는 리팩토링 반영 부탁드리겠습니다.
2단계에서 뵐게요~

2024-01-28 06:45 UTC, merged

2024-01-28 07:35 UTC, sujin0707 commented
> 수진님 1단계 미션 고생하셨습니다! 하지만 리팩토링 사항이 없어보이는데요ㅠㅜ 혹시 push가 누락된 건가요? 2단계에서는 리팩토링 반영 부탁드리겠습니다. 2단계에서 뵐게요~

넵 2단계 미션도 함께 진행하느라 push하는 걸 깜빡했네요ㅠㅠ 2단계 하면서 수정사항도 함께 반영하겠습니다