[뉴스 뷰어 페이지 1단계] - 곽가영 미션 제출합니다.
LIN-KHU/javascript-newsviewer pull request #4
Opened 2024-01-22 08:20 UTC by gykwak03

안녕하세요. 

CSS 정리하고 기사 자세히보기 탭 구현이 필요합니댜.
API 구현이 지체되어 늦어졌던 것 같습니다. 

감사합니다.

2024-01-24 04:05 UTC, tkdrb12 requested changes
안녕하세요 가영님!
리뷰가 늦어 죄송합니다ㅠㅜ🙇‍♂️

이번에 처음 비동기 처리를 접하셨기 때문에 많이 까다로우셨죠?
해당 내용은 깔끔하게 코드를 작성하기 쉽지 않아 여러 라이브러리를 많이 사용하는데요
라이브러리를 사용하지 않고 코드를 작성하기 어려웠을거에요ㅜㅠ
하지만 비동기는 여러 프로그래밍의 핵심이 되는 부분인 만큼 비동기 처리를 잘 다루신다면 그만큼 코딩 실력이 많이 향상될거라 생각합니다.

리뷰를 할 때 꼭 제 의견이 무조건적으로 옳은건 아니니 고민해보시고 의문이 드는 건 질문해주시길 바랍니다.  1단계 미션 고생하셨습니다. 😄

2024-01-24 04:05 UTC, tkdrb12 commented on index.html
> +    <script src="index.js"></script>
따로 스크립트 파일을 html파일내에 삽입한 이유가 있나요??

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +  }
textContent의 타입을 string으로 고정하기 위해 다음과 같이 코드를 작성해주신건가요? 디폴트 파라미터를 정의해주 신 것 아주 좋습니다! 

해당 방법외에도 
```
if (typeof textContent === "string") throw new Error();
```
다음과 같이 타입 가드를 사용하거나

```
element.textContent = textContent ?? ""
```

와 같이 nullish 연산자를 활용하는 방법도 있습니다.

여러 방법들을 학습하시고 가장 최적의 방법이라 생각되는 방법을 활용해보셨으면 좋겠습니다!

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +  }
시간이 된다면 재사용할 수 있는 코드 단락을 따로 클래스로 분리해보는 것을 추천합니다.
예를 들어 페이자가 여러개라고 생각하면 header, nav는 해당 페이지 국한하지 않고 다른 페이지에서도 사용할수가 있잖아요?
이때 해당 `컴포넌트`를 따로 분리해서 관리하면 재사용을 편하게 할 수가 있습니다!

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +    this.appElement.appendChild(underline2);
createElement로 element를 여러개 만들어 관리할 수도 있지만

```
this.element.innerHTML = `<div><img/><p>치킨<p></div>`
```
다음과 같이 html 마크업을 문자열로 직접 정의할 수도 있습니다.
좀 더 가독성에 좋다고 생각하는 쪽을 택해서 사용하시면 되겠습니다.

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +            article.publishedAt || "No Date"
빈값 일 경우 특정 문자열로 초기화를 해주셨군요 이런 부분이 바로 UX에 직접적으로 관여하는 부분이죠!👍

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +  }
해당 코드 단락에서 api데이터를 불러와 받아오는 기능만을 추출한다면 클래스의 영향을 받지 않고 독립적으로 사용할 수 있는 `순수함수`로 사용할 수 있습니다.
코드의 결합성을 낮춘다면 해당 코드를 다른 부분에서 사용할 때 재사용이 편하겠죠? 

분리해서 src 폴더 내의 별개의 파일로 관리해보도록 할까요?

2024-01-24 04:05 UTC, tkdrb12 commented on src/styles/index.css
> +}
마우스 오버 효과 아주 좋습니다~

2024-01-24 04:05 UTC, tkdrb12 commented on src/styles/index.css
> +}
버튼 기본 스타일을 초기화하기 위해서는 `all: unset;` 속성만 추가해주시면 됩니다.

하지만 모든 요소를 일일이 기본 스타일을 초기화 하면 불편하잖아요? 그래서 해당 스타일 초기화를 모아놓은 내용을 reset.css(파일명은 달라질 수 있어요) 파일로 따로 관리하게 될겁니다!

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +      await Promise.all(apiPromises);
해당 Promise.all 라인은 유의미하게 동작하지 않아 보이는데 사용하신 이유가 있을까요?

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +        }
response.ok란 의미는 무엇일까요?

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +  }
만약 해당 코드 단락에서 async 키워드를 사용하지 않는다면
```
  start() {
    this.apiManager().then(()=> this.createAndPutContents());
  }
``` 
다음과 같이 사용해볼 수 있겠네요

만약 all 메소드를 사용하고 싶으셨다면 다음과 같이 사용하면 되겠습니다.
```
  start() {
    this.apiManager().then(()=> this.createAndPutContents()).all(()=>console.log("api응답완료"));
  }
```

2024-01-24 04:05 UTC, tkdrb12 commented on src/index.js
> +    const apiKey = "37e4270349374e67858fd355884ef83c";
api key는 process.env.API_KEY를 사용해서 가져오도록 수정해주세요

2024-01-24 04:05 UTC, tkdrb12 commented on src/styles/index.css
> +}
클래스는 id값과는 다르게 여러 요소들이 동시에 가지고 있을 수 있습니다.

클래스명 image1, image2를 image로 통일하셔서 사용해주면 되겠습니다!

2024-01-24 04:05 UTC, tkdrb12 commented on src/styles/index.css
> +}
해당 부분도 위에 언급과 코멘트와 동일합니다!

2024-01-26 09:38 UTC, gykwak03 commented on index.html
> +    <script src="index.js"></script>
앗 불필요한 코드 같습니다 삭제하겠습니다 !

2024-01-26 09:43 UTC, gykwak03 commented on src/index.js
> +  }
앗 넵 ||는 알았는데 nullish 연산자도 비슷한 개념이군요  null이나 undefined일 때에만 반환한다는 차이점이 있네요 덕분에 알아갑니다!!

2024-01-26 16:05 UTC, gykwak03 commented on src/index.js
> +  }
넵 수정해보도록 하겠습니다!!

2024-01-26 16:19 UTC, gykwak03 commented on src/index.js
> +    this.appElement.appendChild(underline2);
가시적인 코드여서 더 좋은 것 같습니다! 
그런데 저 경우에선 classList.add()를 어떻게 적용하나요 ..??

2024-01-26 16:20 UTC, gykwak03 commented on src/index.js
> +            article.publishedAt || "No Date"
ㅋㅋㅋ감사합니당 ㅎㅎ

2024-01-26 16:26 UTC, gykwak03 commented on src/index.js
> +        }
응답이 정상적으로 불러와졌는지 확인하는 변수입니다! HTTP 상태 코드가 200번대일 때 response.ok는 true가 되고, 400번대 등 잘 불러와지지 않았을 때는 false가 됩니다.

2024-01-26 18:14 UTC, gykwak03 commented on src/index.js
> +  }
오 넵 이렇게도 한번 짜보겠습니다 !!

2024-01-26 18:15 UTC, gykwak03 commented on src/index.js
> +    const apiKey = "37e4270349374e67858fd355884ef83c";
앗 넵 수정하겠습니다!!

2024-01-26 18:25 UTC, gykwak03 commented on src/styles/index.css
> +}
넵 수정했습니다!!

2024-01-26 18:25 UTC, gykwak03 commented on src/styles/index.css
> +}
넵!!

2024-01-28 06:41 UTC, tkdrb12 approved these changes
전반적으로 코드 가독성이 향상된 것 같네요 좋아요!
중간에 확인하지 않은 리뷰도 있어 보이던데 리뷰 갯수가 많을 때는 일부 리뷰는 load more 버튼을 클릭해야 다 확인할 수 있습니다!
1단계 미션 고생하셨고 2단계 미션에서 뵐게요~

2024-01-28 06:41 UTC, merged

2024-01-28 06:46 UTC, tkdrb12 commented on src/index.js
> +    this.appElement.appendChild(underline2);
조금 코드가  난잡해질 수 도 있겠지만 <div class ="underline"> 이런식으로 태그에 직접적으로 클래스를 삽입하면 되겠습니다!